import re
str3="akhil kumar ahil_ +n10484 * ()"
a=re.findall("\Aak",str3)
print(a)
a=re.findall(r"kumar\b",str3)
print(a)
a=re.findall(r"\Bhil",str3)
print(a)
a=re.findall("\d",str3)
print(a)
a=re.findall("\D",str3)
print(a)
a=re.findall("\s",str3)
print(a)
a=re.findall("\S",str3)
print(a)
a=re.findall(r"um\B",str3)
print(a)
a=re.findall("\w",str3)
print(a)
a=re.findall("\W",str3)
print(a)
a=re.findall("[,]",str3)
print(a)
str4="akjijeif kumar"
print(re.findall("r\Z",str4))
print(re.findall("\Aa",str4))
